In [2]:
import numpy as np
a=np.array([0,1,2,3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
#timing python list
l=range(1000)
%timeit [i**2 for i in l]

347 µs ± 14.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
b=np.arange(1000)
%timeit a**2

514 ns ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
a=np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [6]:
a.ndim

1

In [7]:
a.shape

(4,)

In [8]:
len(a)

4

In [9]:
b=np.array([[0,1,2],[3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [12]:
len(b)

2

In [13]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
c.ndim

3

In [15]:
c.shape

(2, 2, 2)

In [16]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [18]:
a=np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [23]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [24]:
a=np.random.rand(4)
a

array([0.0235511 , 0.30761114, 0.88013835, 0.45317717])

In [25]:
a=np.random.randn(4)
a

array([ 0.65992794,  0.51502424, -1.55238493,  1.04334743])

In [26]:
#BASIC DATA TYPES
a=np.arange(10)
a.dtype

dtype('int32')

In [27]:
d=np.array([1+2j,2+4j])
print(d.dtype)

complex128


In [28]:
b=np.array([True,False,True,False])
print(b.dtype)

bool


In [29]:
s=np.array(['Ram','Robert','Rahim'])
s.dtype

dtype('<U6')

In [30]:
a=np.arange(10)
print(a[5])

5


In [31]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [32]:
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [33]:
a=np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a[1:8:2]

array([1, 3, 5, 7])

In [35]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [36]:
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [37]:
#copies and Views
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [39]:
np.shares_memory(a,b)

True

In [40]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [41]:
a #a also gets modified

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [42]:
#force copy
a=np.arange(10)
c=a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [43]:
np.shares_memory(a,c)

False

In [44]:
c[0]=10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Fancy indexing
NumPy arrays can be indexed with slices,but also with boolean or integers arrays(masks).This method is called fancy indexing.It creates copies not views.

In [45]:
a=np.random.randint(1,20,15)
a

array([ 8,  5,  1,  7, 16,  9, 11,  5,  8, 11,  7, 12,  1, 11, 11])

In [46]:
mask=(a%2==0)

In [47]:
extract_from_a=a[mask]
extract_from_a

array([ 8, 16,  8, 12])

### Indexing with a mask can be very useful to assign a new value to a sub-array

In [48]:
a[mask]=-1
a

array([-1,  5,  1,  7, -1,  9, 11,  5, -1, 11,  7, -1,  1, 11, 11])

### indexing with an array of integers.

In [49]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
#Indexing can be done with an array of integers.
a[[2,3,4,2]]

array([20, 30, 40, 20])

In [51]:
#assigning new values to array at perticular positions
a[[9,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

# Arithmetic Operations

In [52]:
a=np.array([1,2,3,4])
#scalar addition
a+1

array([2, 3, 4, 5])

In [53]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

#### All airthmetic operates elementwise

In [54]:
b=np.ones(4)+1
print(a)
print(b)
#Element wise substraction
a-b

[1 2 3 4]
[2. 2. 2. 2.]


array([-1.,  0.,  1.,  2.])

In [55]:
a*b

array([2., 4., 6., 8.])

In [56]:
#Matrix multiplication
c=np.diag([1,2,3,4])
print(c*c)
print("*****************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [57]:
#comparing two matrix
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
a==b


array([False,  True, False,  True])

In [58]:
a>b

array([False, False,  True, False])

In [59]:
#array-wise comparisons
a=np.array([1,2,3,4])
b=np.array([5,2,2,3])
c=np.array([1,2,3,4])
np.array_equal(a,c)

True

In [60]:
np.array_equal(a,b)

False

### Logical Operations


In [61]:
a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [62]:
np.logical_and(a,b)

array([ True, False, False, False])

#### Transcendental functions:

In [63]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [64]:
np.log(a)

C:\Users\Jayaraj\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [65]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

#### Shape mismatch

In [66]:
a=np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

# Basic Reduction
##### computing sums

In [67]:
x=np.array([1,2,3,4])
np.sum(x)

10

In [68]:
#sum by rows and by coloums
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [69]:
x.sum(axis=0) #coloumn first dimension

array([3, 3])

In [70]:
x.sum(axis=1)#rows(secound dimension)

array([2, 4])

#### other reductions

In [71]:
x=np.array([1,2,3,4])
x.min()

1

In [72]:
x.max()

4

In [73]:
#index of min element
x.argmin()

0

In [74]:
#index of min element
x.argmax()

3

#### Logical operations
        
    

In [75]:
#logical and
np.all([True,True,False])

False

In [76]:
#logical or
np.any([True,False,False])

True

In [77]:
a=np.zeros([50,50])
np.any(a!=0)

False

In [78]:
np.all(a==a)  

True

In [79]:
a=np.array([1,2,3,2])
b=np.array([2,2,3,2])
c=np.array([6,4,4,5])
(((a<=b) & (b<=c))).all()

True

### Statistics

In [80]:
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [81]:
print(np.median(x))
print(np.median(y,axis=-1))#last axis which is rows
print(np.median(y,axis=1))#axis->0 axis->1
print(np.median(y,axis=0))

1.5
[2. 5.]
[2. 5.]
[3. 4. 2.]


In [82]:
x.std()

0.82915619758885

#### Example

Data in popoulations.txt describes the populations of hares nad lynxes (and carrots) in northern Canada suring 20 years.

In [83]:
#load data into numpy arrray object
data=np.loadtxt('populations.txt')

In [84]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [85]:
year,hares,lynxes,carrots=data.T#columns to variavles
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [86]:
#The mean population over time
populations = data[:,1:]
populations 

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [87]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [88]:
np.argmax(populations,axis=0)

array([3, 4, 0], dtype=int64)

In [89]:
np.argmax(populations,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2],
      dtype=int64)

### Broadcasting

In [90]:
a=np.tile(np.arange(0,40,10),(3,1))
print(a)
print("**************")
a=a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
**************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [91]:
b=np.array([0,1,2])
b

array([0, 1, 2])

In [92]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [93]:
a=np.arange(0,40,10)
a.shape

(4,)

In [94]:
a=a[:,np.newaxis]
a.shape

(4, 1)

In [95]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [96]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

# Array shape manipulation

#### Flattening

In [105]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [106]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [107]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

#### Reshaping

In [109]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [110]:
b=a.ravel()
print(b)

[1 2 3 4 5 6]


In [111]:
b=b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
b[0,0]=100
a

array([[100,   2,   3],
       [  4,   5,   6]])

 ## reshape may also return a copy!:

In [114]:
a=np.zeros((3,2))
b=a.T.reshape(3*2)
b[0]=50
print(b)
print(a)

[50.  0.  0.  0.  0.  0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


### Adding a Dimension
Indexing with the np.newaxis objects allows us to add an axis to an array
newaxis is used to increase the dimension of the existing array by one more dimension,when used once.thus,
1D array will become 2D array.
2D array will become 3D arrray.
and so on.

In [117]:
z=np.array([1,2,3])
z

array([1, 2, 3])

In [118]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

#### Dimension Shuffling

In [122]:
a=np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [123]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [124]:
a[0,2,1]

5

#### Resizing

In [126]:
a=np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

##### However,it must not be reffered to somewhere else:

In [129]:
b=a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

### Sorting Data

In [130]:
#sorting along an axis:
a=np.array([[5,4,6],[2,3,2]])
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [131]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [ ]:
#sorting with fancy indexing
a=np.array([4,3,1,2])
j=np.argsort(a)
